services:
  mysql:
    image: mysql:8.4
    platform: linux/amd64
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - backend

  redis-cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - backend

networks:
  backend:
    name: email_app_network
    driver: bridge

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
