version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: jimdev
      POSTGRES_PASSWORD: secret
    networks:
      - backend

  redis-cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

networks:
  backend:
    name: finance_network
    driver: bridge

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
